export const SET_CITIES_TO_STORE = "SET_CITIES_TO_STORE";
export const RESET_SEARCH = "RESET_SEARCH";
export const SET_CITY_BANKS_INFO = "SET_CITY_BANKS_INFO";
export const SET_FILTERS = "SET_FILTERS";
export const FILTER_MAP_DATA = "FILTER_MAP_DATA";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_ACTIVE_BRANCH = "SET_ACTIVE_BRANCH";
export const SET_CURRENT_BOUNDS = "SET_CURRENT_BOUNDS";
export const TOGGLE_IS_FILTER_OPEN = "TOGGLE_IS_FILTER_OPEN";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";

