export { ReactComponent as UnsuccessIcon } from "./static/unsuccess.svg";
export { ReactComponent as SelfieSuccessIcon } from "./static/successIdSelfie.svg";
export { ReactComponent as GirlSuccessIcon } from "./static/black-girl.svg";
export { ReactComponent as MainLogoIcon } from "./static/mainLogo_v2.svg";
export { CreditCardIcon } from "./CreditCardIcon";
export { ReactComponent as USD } from "./static/USD.svg";
export { ReactComponent as PLN } from "./static/PLN.svg";
export { ReactComponent as EUR } from "./static/EUR.svg";
export { ReactComponent as RightArrowI } from "./static/right-arrow.svg";
export { ReactComponent as CopyIcon } from "./static/copy.svg";
export { ReactComponent as EditorIcon } from "./static/editor.svg";
export { ReactComponent as ClearInputIcon } from "./static/clear-input.svg";
export { ReactComponent as CongratulationsIcon } from "./static/congratulations.svg";
export { CloseIcon } from "./CloseIcon";
export { ReactComponent as Browser } from "./static/Browser.svg";
export { ReactComponent as GroupOfCircles } from "./static/Group.svg";
export { ReactComponent as IntroPageBlockThreeImg } from "./static/introPageBlockThreeImg.svg";
export { ReactComponent as CellPhoneIcon } from "./static/cell-phone.svg";
export { ReactComponent as Google } from "./static/google.svg";
export { ReactComponent as Apple } from "./static/apple.svg";
export { ReactComponent as Facebook } from "./static/facebook.svg";
export { ReactComponent as Instagram } from "./static/instagram.svg";
export { ReactComponent as Twitter } from "./static/twitter.svg";
export { ReactComponent as Skype } from "./static/skype.svg";
export { ReactComponent as Linkedin } from "./static/linkedin.svg";
export { ReactComponent as KeyBoardArrowDown } from "./static/keaybord_arrow_down.svg";
export { ReactComponent as ArrowRightBlue } from "./static/arrow-right-blue.svg";
